import { CountryCode } from './countryCode';

export const COUNTRYCODES: CountryCode[] = [
  {country:"IN",code: "91",countryName:"India",id:1 },
  { country: "BD", code: "880",countryName:"Bangladesh",id:2 },
  { country: "BE", code: "32",countryName:"Belgium" ,id:3 },
  { country: "BF", code: "226" ,countryName:"Burkina Faso",id:4 },
  { country: "BG", code: "359",countryName:"Bulgaria",id:5  },
  { country: "BA", code: "387" ,countryName:"Bosnia and Herzegovina",id:6 },
  { country: "BB", code: "+1-246",countryName:"Barbados",id:7  },
  { country: "WF", code: "681",countryName:"Wallis and Futuna",id:8  },
  { country: "BL", code: "590",countryName:"Saint Barthelemy",id:9  },
  { country: "BM", code: "+1-441",countryName:"Bermuda" ,id:10 },
  { country: "BN", code: "673",countryName:"Brunei",id:11  },
  { country: "BO", code: "591",countryName:"Bolivia",id:12  },
  { country: "BH", code: "973" ,countryName:"Bahrain",id:13 },
  {country: "BI", code: "257",countryName:"Burundi",id:14 },
  {country: "BJ", code: "975",countryName:"Benin",id:15 },
  {country: "JM", code: "+1-876",countryName:"Jamaica" ,id:16},
  {country: "BV", code: "",countryName:"Bouvet Island",id:17 },
  {country: "BW", code: "267",countryName:"Botswana",id:18 },
  {country: "WS", code: "685",countryName:"Samoa",id:19 },
  {country: "BQ", code: "599",countryName:"Bonaire, Saint Eustatius and Saba",id:20 },
  {country: "BR", code: "55",countryName:"Brazil" ,id:21},
  {country: "BS", code: "+1-242",countryName:"Bahamas",id:22 },
  {country: "JE", code: "+44-1534",countryName:"Jersey",id:23 },
  {country: "BY", code: "375",countryName:"Belarus",id:24 },
  {country: "BZ", code: "501",countryName:"Belize",id:25 },
  {country: "RU", code: "7",countryName:"Russia",id:26},
  {country: "RW", code: "250",countryName:"Rwanda",id:27 },
  {country: "RS", code: "381",countryName:"Serbia" ,id:28},
  {country: "TL", code: "670",countryName:"East Timor",id:29 },
  {country: "RE", code: "262",countryName:"Reunion",id:30 },
  {country: "TM", code: "993",countryName:"Turkmenistan",id:31 },
  {country: "TJ", code: "992",countryName:"Tajikistan",id:32 },
  {country: "RO", code: "40",countryName:"Romania",id:33 },
  {country: "TK", code: "690",countryName:"Tokelau",id:34 },
  {country: "GW", code: "245",countryName:"Guinea-Bissau",id:35 },
  {country: "GU", code: "+1-671",countryName:"Guam",id:36 },
  {country: "GT", code: "502",countryName:"Guatemala",id:37 },
  {country: "GS", code: "",countryName:"South Georgia and the South Sandwich Islands",id:38 },
  {country: "GR", code: "30",countryName:"Greece" ,id:39},
  {country: "GQ", code: "240",countryName:"Equatorial Guinea",id:40 },
  {country: "GP", code: "590",countryName:"Guadeloupe" ,id:41},
  {country: "JP", code: "81",countryName:"Japan" ,id:42},
  {country: "GY", code: "592",countryName:"Guyana",id:43 },
  {country: "GG", code: "+44-1481",countryName:"Guernsey",id:44 },
  {country: "GF", code: "594",countryName:"French Guiana",id:45 },
  {country: "GE", code: "995",countryName:"Georgia",id:46 },
  {country: "GD", code: "+1-473",countryName:"Grenada" ,id:47},
  {country: "GB", code: "44",countryName:"United Kingdom",id:48 },
  {country: "GA", code: "241",countryName:"Gabon" ,id:49},
  {country: "SV", code: "503",countryName:"El Salvador",id:50 },
  {country: "GN", code: "224",countryName:"Guinea",id:51 },
  {country: "GM", code: "220",countryName:"Gambia",id:52 },
  {country: "GL", code: "299",countryName:"Greenland",id:53},
  {country: "GI", code: "350",countryName:"Gibraltar",id:54 },
  {country: "GH", code: "233",countryName:"Ghana",id:55 },
  {country: "OM", code: "968",countryName:"Oman",id:56 },
  {country: "TN", code: "216",countryName:"Tunisia",id:57 },
  {country: "JO", code: "962",countryName:"Jordan",id:58 },
  {country: "HR", code: "385",countryName:"Croatia",id:59 },
  {country: "HT", code: "509",countryName:"Haiti",id:60 },
  {country: "HU", code: "36",countryName:"Hungary",id:61 },
  {country: "HK", code: "852",countryName:"Hong Kong",id:62 },
  {country: "HN", code: "504",countryName:"Honduras",id:63 },
  {country: "HM", code: "",countryName:"Heard Island and McDonald Islands",id:64 },
  {country: "VE", code: "58",countryName:"Venezuela",id:65 },
  {country: "PR", code: "+1-787 and 1-939",countryName:"Puerto Rico",id:66 },
  {country: "PS", code: "970",countryName:"Palestinian Territory",id:67 },
  {country: "PW", code: "680",countryName:"Palau",id:68 },
  {country: "PT", code: "351",countryName:"Portugal",id:69 },
  {country: "SJ", code: "47",countryName:"Svalbard and Jan Mayen",id:70 },
  {country: "PY", code: "595",countryName:"Paraguay",id:71 },
  {country: "IQ", code: "964",countryName:"Iraq",id:72 },
  {country: "PA", code: "507",countryName:"Panama",id:73 },
  {country: "PF", code: "689",countryName:"French Polynesia",id:74 },
  {country: "PG", code: "675",countryName:"Papua New Guinea",id:75 },
  {country: "PE", code: "51",countryName:"Peru",id:76 },
  {country: "PK", code: "92",countryName:"Pakistan",id:77 },
  {country: "PH", code: "63",countryName:"Philippines",id:78 },
  {country: "PN", code: "870",countryName:"Pitcairn",id:79 },
  {country: "PL", code: "48",countryName:"Poland",id:80},
  {country: "PM", code: "508",countryName:"Saint Pierre and Miquelon",id:81 },
  {country: "ZM", code: "260",countryName:"Zambia",id:82 },
  {country: "EH", code: "212 ",countryName:"Western Sahara",id:83 },
  {country: "EE", code: "372",countryName:"Estonia",id:84 },
  {country: "EG", code: "20",countryName:"Egypt",id:85},
  {country: "ZA", code: "27",countryName:"South Africa",id:86 },
  {country: "EC", code: "593",countryName:"Ecuador",id:87 },
  {country: "IT", code: "39",countryName:"Italy",id:88 },
  {country: "VN", code: "84",countryName:"Vietnam",id:89 },
  {country: "SB", code: "677",countryName:"Solomon Islands",id:90 },
  {country: "ET", code: "251",countryName:"Ethiopia",id:91 },
  {country: "SO", code: "252",countryName:"Somalia",id:92 },
  {country: "ZW", code: "263",countryName:"Zimbabwe",id:93 },
  {country: "SA", code: "966",countryName:"Saudi Arabia" ,id:94},
  {country:"ES" ,code: "34",countryName:"Spain",id:95 }, 
  {country:"ER",code: "291",countryName:"Eritrea",id:96 },
  {country:"MD",code: "373",countryName:"Moldova" ,id:97},
  {country: "MG",code: "261",countryName:"Madagascar",id:98 },
  {country: "MF",code: "590",countryName:"Saint Martin",id:99 },
  {country: "MA",code: "212",countryName:"Morocco",id:100},
  {country:"MC",code: "377",countryName:"Monaco",id:101 },
  {country:"UZ",code: "998",countryName:"Uzbekistan",id:102 },
  {country: "MM",code: "95",countryName:"Myanmar",id:103 },
  {country:"ML",code: "223",countryName:"Mali",id:104 },
  {country:"MO",code: "853",countryName:"Macao",id:105 }, 
  {country:"MN",code: "976",countryName:"Mongolia",id:106 },
  {country:"MH",code: "692",countryName:"Marshall Islands",id:107 },
  {country:"MK",code: "389",countryName:"Macedonia",id:108 },
  {country:"MU",code: "230",countryName:"Mauritius",id:109 },
  {country:"MT",code: "356",countryName:"Malta",id:110},
  {country: "MW",code: "265",countryName:"Malawi",id:111 },
  {country: "MV",code: "960",countryName:"Maldives",id:112 },
  {country:"MQ",code: "596",countryName:"Martinique",id:113 },
  {country:"MP",code: "+1-670",countryName:"Northern Mariana Islands" ,id:114},
  {country: "MS",code: "+1-664",countryName:"Montserrat" ,id:115},
  {country:"MR",code: "222",countryName:"Mauritania",id:116 },
  {country:"IM",code: "+44-1624",countryName:"Isle of Man" ,id:117},
  {country:"UG",code: "256",countryName:"Uganda" ,id:118},
  {country:"TZ",code: "255",countryName:"Tanzania" ,id:119},
  {country:"MY",code: "60",countryName:"Malaysia",id:120 },
  {country:"MX",code: "52",countryName:"Mexico",id:121 },
  {country: "IL",code: "972",countryName:"Israel" ,id:122},
  {country:"FR",code: "33",countryName:"France",id:123 },
  {country:"IO",code: "246",countryName:"British Indian Ocean Territory",id:124 },
  {country:"SH",code: "290",countryName:"Saint Helena",id:125 },
  {country:"FI",code: "358",countryName:"Finland",id:126 },
  {country:"FJ",code: "679",countryName:"Fiji" ,id:127},
  {country:"FK",code: "500",countryName:"Falkland Islands",id:128 },
  {country:"FM",code: "691",countryName:"Micronesia",id:129 },
  {country:"FO",code: "298",countryName:"Faroe Islands",id:130 },
  {country: "NI",code: "505",countryName:"Nicaragua",id:131 },
  {country: "NL",code: "31",countryName:"Netherlands",id:132 },
  {country: "NO",code: "47",countryName:"Norway",id:133 },
  {country: "NA",code: "264",countryName:"Namibia",id:134 },
  {country: "VU",code: "678",countryName:"Vanuatu",id:135 },
  {country: "NC",code: "687",countryName:"New Caledonia",id:136 },
  {country: "NE",code: "227",countryName:"Niger",id:137 },
  {country: "NF",code: "672",countryName:"Norfolk Island",id:138 },
  {country: "NG",code: "234",countryName:"Nigeria",id:139 },
  {country: "NZ",code: "64",countryName:"New Zealand",id:140 },
  {country: "NP",code: "977",countryName:"Nepal",id:141 },
  {country: "NR",code: "674",countryName:"Nauru",id:142 }, 
  {country:"NU",code: "683",countryName:"Niue",id:143 }, 
  {country:"CK",code: "682",countryName:"Cook Islands",id:144 },
  {country: "XK",code: "",countryName:"Kosovo",id:145 }, 
  {country:"CI",code: "225",countryName:"Ivory Coast",id:146 },
  {country: "CH",code: "41",countryName:"Switzerland",id:147 }, 
  {country:"CO",code: "57",countryName:"Colombia" ,id:148}, 
  {country:"CN",code: "86",countryName:"China",id:149 },
  {country: "CM",code: "237",countryName:"Cameroon",id:150 },
  {country: "CL",code: "56",countryName:"Chile",id:151 },
  {country: "CC",code: "61",countryName:"Cocos Islands",id:152 },
  {country: "CA",code: "1",countryName:"Canada",id:153 },
  {country: "CG",code: "242",countryName:"Republic of the Congo",id:154 },
  {country: "CF",code: "236",countryName:"Central African Republic",id:155 },
  {country: "CD",code: "243",countryName:"Democratic Republic of the Congo",id:156 },
  {country: "CZ",code: "420",countryName:"Czech Republic" ,id:157}, 
  {country:"CY",code: "357",countryName:"Cyprus",id:158 },
  {country: "CX",code: "61",countryName:"Christmas Island",id:159 },
  {country: "CR",code: "506",countryName:"Costa Rica",id:160 },
  {country: "CW",code: "599",countryName:"Curacao",id:161 },
  {country: "CV",code: "238",countryName:"Cape Verde",id:162 },
  {country: "CU",code: "53",countryName:"Cuba",id:163 }, 
  {country:"SZ",code: "268",countryName:"Swaziland",id:164 }, 
  {country:"SY",code: "963",countryName:"Syria",id:165 },
  {country: "SX",code: "599",countryName:"Sint Maarten",id:166 },
  {country: "KG",code: "996",countryName:"Kyrgyzstan",id:167 }, 
  {country:"KE",code: "254",countryName:"Kenya",id:168 },
  {country: "SS",code: "211",countryName:"South Sudan",id:169 },
  {country: "SR",code: "597",countryName:"Suriname",id:170 },
  {country: "KI",code: "686",countryName:"Kiribati" ,id:171},
  {country: "KH",code: "855",countryName:"Cambodia" ,id:172},
  {country: "KN",code: "+1-869",countryName:"Saint Kitts and Nevis",id:173 }, 
  {country:"KM",code: "269",countryName:"Comoros",id:174 },
  {country: "ST",code: "239",countryName:"Sao Tome and Principe",id:175 },
  {country: "SK",code: "421",countryName:"Slovakia",id:176 },
  {country: "KR",code: "82",countryName:"South Korea" ,id:177},
  {country: "SI",code: "386",countryName:"Slovenia" ,id:178}, 
  {country:"KP",code: "850",countryName:"North Korea",id:179 }, 
  {country:"KW",code: "965",countryName:"Kuwait",id:180 },
  {country: "SN",code: "221",countryName:"Senegal",id:181 }, 
  {country:"SM",code: "378",countryName:"San Marino",id:182 },
  {country: "SL",code: "232",countryName:"Sierra Leone",id:183 }, 
  {country:"SC",code: "248",countryName:"Seychelles",id:184 }, 
  {country:"KZ",code: "7",countryName:"Kazakhstan",id:185 },
  {country: "KY",code: "+1-345",countryName:"Cayman Islands" ,id:186}, 
  {country:"SG",code: "65",countryName:"Singapore" ,id:187}, 
  {country:"SE",code: "46",countryName:"Sweden" ,id:188}, 
  {country:"SD",code: "249",countryName:"Sudan",id:189 }, 
  {country:"DO",code: "+1-809 and 1-829",countryName:"Dominican Republic",id:190},
  {country: "DM",code: "+1-767",countryName:"Dominica",id:191 }, 
  {country:"DJ",code: "253",countryName:"Djibouti",id:192 },
  {country: "DK",code: "45",countryName:"Denmark" ,id:193},
  {country: "VG",code: "+1-284",countryName:"British Virgin Islands",id:194 },
  {country: "DE",code: "49",countryName:"Germany",id:195 },
  {country: "YE",code: "967",countryName:"Yemen",id:196 }, 
  {country:"DZ",code: "213",countryName:"Algeria",id:197 }, 
  {country:"US",code: "1",countryName:"United States",id:198 }, 
  {country:"UY",code: "598",countryName:"Uruguay",id:199 }, 
  {country:"YT",code: "262",countryName:"Mayotte",id:200 }, 
  {country:"UM",code: "1",countryName:"United States Minor Outlying Islands",id:201 },
  {country: "LB",code: "961",countryName:"Lebanon",id:202 },
  {country: "LC",code: "+1-758",countryName:"Saint Lucia",id:203 }, 
  {country:"LA",code: "856",countryName:"Laos",id:204 }, 
  {country:"TV",code: "688",countryName:"Tuvalu",id:205 }, 
  {country:"TW",code: "886",countryName:"Taiwan",id:206 },
  {country: "TT",code: "+1-868",countryName:"Trinidad and Tobago",id:207 }, 
  {country:"TR",code: "90",countryName:"Turkey",id:208 }, 
  {country:"LK",code: "94",countryName:"Sri Lanka",id:209 }, 
  {country:"LI",code: "423",countryName:"Liechtenstein",id:210 }, 
  {country:"LV",code: "371",countryName:"Latvia",id:211 }, 
  {country:"TO",code: "676",countryName:"Tonga",id:212 }, 
  {country:"LT",code: "370",countryName:"Lithuania",id:213 },
  {country: "LU",code: "352",countryName:"Luxembourg",id:214 },
  {country: "LR",code: "231",countryName:"Liberia",id:215 }, 
  {country:"LS",code: "266",countryName:"Lesotho",id:216 }, 
  {country:"TH",code: "66",countryName:"Thailand",id:217 },
  {country: "TF",code: "",countryName:"French Southern Territories",id:218 },
  {country: "TG",code: "228",countryName:"Togo",id:219 },
  {country: "TD",code: "235",countryName:"Chad",id:220 },
  {country: "TC",code: "+1-649",countryName:"Turks and Caicos Islands",id:221 },
  {country: "LY",code: "218",countryName:"Libya",id:222 }, 
  {country:"VA",code: "379",countryName:"Vatican" ,id:223},
  {country:"VC",code: "+1-784",countryName:"Saint Vincent and the Grenadines",id:224 },
  {country:"AE",code: "971",countryName:"United Arab Emirates",id:225 },
  {country:"AD",code: "376",countryName:"Andorra",id:226 },
  {country:"AG",code: "+1-268",countryName:"Antigua and Barbuda",id:227 },
  {country: "AF",code: "93",countryName:"Afghanistan",id:228 },
  {country:"AI",code: "+1-264",countryName:"Anguilla",id:229 },
  {country:"VI",code: "+1-340",countryName:"U.S. Virgin Islands",id:230 },
  {country:"IS",code: "354",countryName:"Iceland",id:231 },
  {country:"IR",code: "98",countryName:"Iran",id:232 },
  {country: "AM",code: "374",countryName:"Armenia",id:233 },
  {country: "AL",code: "355",countryName:"Albania",id:234 },
  {country:"AO",code: "244",countryName:"Angola" ,id:235},
  {country:"AQ",code: "",countryName:"Antarctica",id:236 },
  {country:"AS",code: "+1-684",countryName:"American Samoa",id:237 },
  {country:"AR",code: "54",countryName:"Argentina",id:238 },
  {country: "AU",code: "61",countryName:"Australia",id:239 },
  {country:"AT",code: "43",countryName:"Austria",id:240 },
  {country:"AW",code: "297",countryName:"Aruba",id:241 },
  {country:"AX",code: "+358-18",countryName:"Aland Islands",id:242 },
  {country: "AZ",code: "994",countryName:"Azerbaijan",id:243 },
  {country: "IE",code: "353",countryName:"Ireland",id:244 },
  {country:"ID",code: "62",countryName:"Indonesia",id:245 },
  {country:"UA",code: "380",countryName:"Ukraine",id:246 },
  {country:"QA",code: "974",countryName:"Qatar",id:247 },
  {country: "MZ",code: "258",countryName:"Mozambique",id:248 }
];
